spring.application.name=delivery-api
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.profiles.active=local
springdoc.swagger-ui.url=https://transporte-api-production-df09.up.railway.app/v3/api-docs
server.forward-headers-strategy=framework